-- 依据教育部《全国高等学校名单》（数据截至 2026-06-17，2026-06-18 发布）补齐山东省普通高等学校。
-- 只补缺失的：school.name 上有唯一索引，INSERT IGNORE 保证本迁移可重复执行。
INSERT IGNORE INTO school (name, province_id, status)
SELECT v.name, (SELECT id FROM province WHERE name = '山东'), 1
FROM (
    SELECT '山东大学' AS name UNION ALL
    SELECT '中国海洋大学' UNION ALL
    SELECT '山东科技大学' UNION ALL
    SELECT '中国石油大学（华东）' UNION ALL
    SELECT '青岛科技大学' UNION ALL
    SELECT '济南大学' UNION ALL
    SELECT '青岛理工大学' UNION ALL
    SELECT '山东建筑大学' UNION ALL
    SELECT '齐鲁工业大学' UNION ALL
    SELECT '山东理工大学' UNION ALL
    SELECT '山东农业大学' UNION ALL
    SELECT '青岛农业大学' UNION ALL
    SELECT '山东第二医科大学' UNION ALL
    SELECT '山东第一医科大学' UNION ALL
    SELECT '山东医药大学' UNION ALL
    SELECT '山东中医药大学' UNION ALL
    SELECT '济宁医学院' UNION ALL
    SELECT '山东师范大学' UNION ALL
    SELECT '曲阜师范大学' UNION ALL
    SELECT '聊城大学' UNION ALL
    SELECT '德州学院' UNION ALL
    SELECT '山东航空学院' UNION ALL
    SELECT '鲁东大学' UNION ALL
    SELECT '临沂大学' UNION ALL
    SELECT '泰山学院' UNION ALL
    SELECT '济宁学院' UNION ALL
    SELECT '菏泽学院' UNION ALL
    SELECT '山东财经大学' UNION ALL
    SELECT '山东体育学院' UNION ALL
    SELECT '山东艺术学院' UNION ALL
    SELECT '齐鲁医药学院' UNION ALL
    SELECT '青岛滨海学院' UNION ALL
    SELECT '枣庄学院' UNION ALL
    SELECT '山东工艺美术学院' UNION ALL
    SELECT '青岛大学' UNION ALL
    SELECT '烟台大学' UNION ALL
    SELECT '潍坊学院' UNION ALL
    SELECT '山东警察学院' UNION ALL
    SELECT '山东交通学院' UNION ALL
    SELECT '山东工商学院' UNION ALL
    SELECT '山东女子学院' UNION ALL
    SELECT '烟台南山学院' UNION ALL
    SELECT '潍坊科技学院' UNION ALL
    SELECT '山东英才学院' UNION ALL
    SELECT '青岛恒星科技学院' UNION ALL
    SELECT '青岛黄海学院' UNION ALL
    SELECT '山东现代学院' UNION ALL
    SELECT '山东协和学院' UNION ALL
    SELECT '山东工程职业技术大学' UNION ALL
    SELECT '烟台理工学院' UNION ALL
    SELECT '聊城大学东昌学院' UNION ALL
    SELECT '青岛城市学院' UNION ALL
    SELECT '潍坊理工学院' UNION ALL
    SELECT '山东财经大学燕山学院' UNION ALL
    SELECT '山东石油化工学院' UNION ALL
    SELECT '山东外国语职业技术大学' UNION ALL
    SELECT '泰山科技学院' UNION ALL
    SELECT '山东华宇工学院' UNION ALL
    SELECT '山东外事职业大学' UNION ALL
    SELECT '青岛工学院' UNION ALL
    SELECT '青岛农业大学海都学院' UNION ALL
    SELECT '齐鲁理工学院' UNION ALL
    SELECT '山东财经大学东方学院' UNION ALL
    SELECT '烟台科技学院' UNION ALL
    SELECT '山东政法学院' UNION ALL
    SELECT '齐鲁师范学院' UNION ALL
    SELECT '山东青年政治学院' UNION ALL
    SELECT '青岛电影学院' UNION ALL
    SELECT '山东管理学院' UNION ALL
    SELECT '山东农业工程学院' UNION ALL
    SELECT '康复大学' UNION ALL
    SELECT '淄博职业技术大学' UNION ALL
    SELECT '滨州职业技术大学' UNION ALL
    SELECT '日照职业技术大学' UNION ALL
    SELECT '山东商业职业技术大学' UNION ALL
    SELECT '临沂工学院' UNION ALL
    SELECT '山东科技职业大学' UNION ALL
    SELECT '山东医学高等专科学校' UNION ALL
    SELECT '菏泽医学专科学校' UNION ALL
    SELECT '山东电力高等专科学校' UNION ALL
    SELECT '曲阜远东职业技术学院' UNION ALL
    SELECT '青岛职业技术学院' UNION ALL
    SELECT '威海职业学院' UNION ALL
    SELECT '山东职业学院' UNION ALL
    SELECT '山东劳动职业技术学院' UNION ALL
    SELECT '莱芜职业技术学院' UNION ALL
    SELECT '济宁职业技术学院' UNION ALL
    SELECT '潍坊职业学院' UNION ALL
    SELECT '烟台职业学院' UNION ALL
    SELECT '东营职业学院' UNION ALL
    SELECT '聊城职业技术学院' UNION ALL
    SELECT '山东服装职业学院' UNION ALL
    SELECT '德州科技职业学院' UNION ALL
    SELECT '山东力明科技职业学院' UNION ALL
    SELECT '山东圣翰财贸职业学院' UNION ALL
    SELECT '山东水利职业学院' UNION ALL
    SELECT '山东畜牧兽医职业学院' UNION ALL
    SELECT '青岛飞洋职业技术学院' UNION ALL
    SELECT '东营科技职业学院' UNION ALL
    SELECT '山东交通职业学院' UNION ALL
    SELECT '山东外贸职业学院' UNION ALL
    SELECT '青岛酒店管理职业技术学院' UNION ALL
    SELECT '山东信息职业技术学院' UNION ALL
    SELECT '青岛港湾职业技术学院' UNION ALL
    SELECT '山东胜利职业学院' UNION ALL
    SELECT '山东经贸职业学院' UNION ALL
    SELECT '山东工业职业学院' UNION ALL
    SELECT '山东化工职业学院' UNION ALL
    SELECT '青岛求实职业技术学院' UNION ALL
    SELECT '济南职业学院' UNION ALL
    SELECT '烟台工程职业技术学院' UNION ALL
    SELECT '潍坊工商职业学院' UNION ALL
    SELECT '德州职业技术学院' UNION ALL
    SELECT '枣庄科技职业学院' UNION ALL
    SELECT '淄博师范高等专科学校' UNION ALL
    SELECT '山东中医药高等专科学校' UNION ALL
    SELECT '济南工程职业技术学院' UNION ALL
    SELECT '山东电子职业技术学院' UNION ALL
    SELECT '山东旅游职业学院' UNION ALL
    SELECT '山东铝业职业学院' UNION ALL
    SELECT '泰山职业技术学院' UNION ALL
    SELECT '山东药品食品职业学院' UNION ALL
    SELECT '山东商务职业学院' UNION ALL
    SELECT '山东轻工职业学院' UNION ALL
    SELECT '山东城市建设职业学院' UNION ALL
    SELECT '烟台汽车工程职业学院' UNION ALL
    SELECT '山东司法警官职业学院' UNION ALL
    SELECT '菏泽家政职业学院' UNION ALL
    SELECT '山东传媒职业学院' UNION ALL
    SELECT '临沂职业学院' UNION ALL
    SELECT '枣庄职业学院' UNION ALL
    SELECT '山东理工职业学院' UNION ALL
    SELECT '山东文化产业职业学院' UNION ALL
    SELECT '青岛远洋船员职业学院' UNION ALL
    SELECT '济南幼儿师范高等专科学校' UNION ALL
    SELECT '济南护理职业学院' UNION ALL
    SELECT '泰山护理职业学院' UNION ALL
    SELECT '山东海事职业学院' UNION ALL
    SELECT '潍坊护理职业学院' UNION ALL
    SELECT '潍坊工程职业学院' UNION ALL
    SELECT '菏泽职业学院' UNION ALL
    SELECT '山东艺术设计职业学院' UNION ALL
    SELECT '威海海洋职业学院' UNION ALL
    SELECT '山东特殊教育职业学院' UNION ALL
    SELECT '烟台黄金职业学院' UNION ALL
    SELECT '日照航海工程职业学院' UNION ALL
    SELECT '青岛工程职业学院' UNION ALL
    SELECT '青岛幼儿师范高等专科学校' UNION ALL
    SELECT '烟台幼儿师范高等专科学校' UNION ALL
    SELECT '烟台文化旅游职业学院' UNION ALL
    SELECT '临沂科技职业学院' UNION ALL
    SELECT '青岛航空科技职业学院' UNION ALL
    SELECT '潍坊环境工程职业学院' UNION ALL
    SELECT '滨州科技职业学院' UNION ALL
    SELECT '山东城市服务职业学院' UNION ALL
    SELECT '潍坊食品科技职业学院' UNION ALL
    SELECT '烟台城市科技职业学院' UNION ALL
    SELECT '德州工程职业学院' UNION ALL
    SELECT '日照康养职业学院' UNION ALL
    SELECT '烟台卫生健康职业学院' UNION ALL
    SELECT '山东文化艺术职业学院' UNION ALL
    SELECT '聊城科技职业学院' UNION ALL
    SELECT '济宁汽车工程职业学院' UNION ALL
    SELECT '日照科技职业学院' UNION ALL
    SELECT '枣庄应用技术职业学院' UNION ALL
    SELECT '临沂城市职业学院' UNION ALL
    SELECT '菏泽生物医药职业学院' UNION ALL
    SELECT '济宁卫生健康职业学院' UNION ALL
    SELECT '青岛健康科技职业学院' UNION ALL
    SELECT '德州智能技术职业学院' UNION ALL
    SELECT '滨州健康科技职业学院'
) v;

-- 给本省还没有任何校区的学校补一个「主校区」。
-- 现有 231 个校区里有 121 个叫「主校区」，沿用同一约定；这样学校在「省-校-校区」三级
-- 联动里才可选（没有校区的学校用户根本选不中）。
INSERT INTO campus (school_id, name, status)
SELECT s.id, '主校区', 1
FROM school s
JOIN province p ON p.id = s.province_id
WHERE p.name = '山东'
  AND s.deleted = 0
  AND NOT EXISTS (SELECT 1 FROM campus c WHERE c.school_id = s.id AND c.deleted = 0);
