-- 依据教育部《全国高等学校名单》（数据截至 2026-06-17，2026-06-18 发布）补齐河南省普通高等学校。
-- 只补缺失的：school.name 上有唯一索引，INSERT IGNORE 保证本迁移可重复执行。
INSERT IGNORE INTO school (name, province_id, status)
SELECT v.name, (SELECT id FROM province WHERE name = '河南'), 1
FROM (
    SELECT '华北水利水电大学' AS name UNION ALL
    SELECT '郑州大学' UNION ALL
    SELECT '河南理工大学' UNION ALL
    SELECT '郑州轻工业大学' UNION ALL
    SELECT '河南工业大学' UNION ALL
    SELECT '河南科技大学' UNION ALL
    SELECT '中原工学院' UNION ALL
    SELECT '河南农业大学' UNION ALL
    SELECT '河南科技学院' UNION ALL
    SELECT '河南牧业经济学院' UNION ALL
    SELECT '河南中医药大学' UNION ALL
    SELECT '河南医药大学' UNION ALL
    SELECT '河南大学' UNION ALL
    SELECT '河南师范大学' UNION ALL
    SELECT '信阳师范大学' UNION ALL
    SELECT '周口师范学院' UNION ALL
    SELECT '安阳师范学院' UNION ALL
    SELECT '许昌学院' UNION ALL
    SELECT '南阳师范学院' UNION ALL
    SELECT '洛阳师范学院' UNION ALL
    SELECT '商丘师范学院' UNION ALL
    SELECT '河南财经政法大学' UNION ALL
    SELECT '郑州航空工业管理学院' UNION ALL
    SELECT '黄淮学院' UNION ALL
    SELECT '平顶山学院' UNION ALL
    SELECT '郑州工程技术学院' UNION ALL
    SELECT '洛阳理工学院' UNION ALL
    SELECT '新乡学院' UNION ALL
    SELECT '信阳农林学院' UNION ALL
    SELECT '河南工学院' UNION ALL
    SELECT '安阳工学院' UNION ALL
    SELECT '河南工程学院' UNION ALL
    SELECT '河南财政金融学院' UNION ALL
    SELECT '南阳理工学院' UNION ALL
    SELECT '河南城建学院' UNION ALL
    SELECT '河南警察学院' UNION ALL
    SELECT '黄河科技学院' UNION ALL
    SELECT '郑州警察学院' UNION ALL
    SELECT '郑州科技学院' UNION ALL
    SELECT '郑州工业应用技术学院' UNION ALL
    SELECT '郑州师范学院' UNION ALL
    SELECT '郑州财经学院' UNION ALL
    SELECT '黄河交通学院' UNION ALL
    SELECT '商丘工学院' UNION ALL
    SELECT '河南开封科技传媒学院' UNION ALL
    SELECT '中原科技学院' UNION ALL
    SELECT '信阳学院' UNION ALL
    SELECT '安阳学院' UNION ALL
    SELECT '豫北医学院' UNION ALL
    SELECT '新乡工程学院' UNION ALL
    SELECT '郑州工商学院' UNION ALL
    SELECT '郑州经贸学院' UNION ALL
    SELECT '商丘学院' UNION ALL
    SELECT '郑州商学院' UNION ALL
    SELECT '河南科技职业大学' UNION ALL
    SELECT '郑州升达经贸管理学院' UNION ALL
    SELECT '郑州西亚斯学院' UNION ALL
    SELECT '郑州美术学院' UNION ALL
    SELECT '漯河食品工程职业大学' UNION ALL
    SELECT '河南体育学院' UNION ALL
    SELECT '郑州健康学院' UNION ALL
    SELECT '黄河水利职业技术大学' UNION ALL
    SELECT '河南工业职业技术大学' UNION ALL
    SELECT '河南信息科技学院' UNION ALL
    SELECT '河南应用工程学院' UNION ALL
    SELECT '河南国医学院' UNION ALL
    SELECT '郑州铁路职业技术大学' UNION ALL
    SELECT '河南能源化工学院' UNION ALL
    SELECT '河南职业技术学院' UNION ALL
    SELECT '漯河职业技术学院' UNION ALL
    SELECT '三门峡职业技术学院' UNION ALL
    SELECT '开封大学' UNION ALL
    SELECT '焦作大学' UNION ALL
    SELECT '濮阳职业技术学院' UNION ALL
    SELECT '郑州电力高等专科学校' UNION ALL
    SELECT '许昌职业技术学院' UNION ALL
    SELECT '河南工业和信息化职业学院' UNION ALL
    SELECT '河南水利与环境职业学院' UNION ALL
    SELECT '商丘职业技术学院' UNION ALL
    SELECT '平顶山工业职业技术学院' UNION ALL
    SELECT '周口职业技术学院' UNION ALL
    SELECT '济源职业技术学院' UNION ALL
    SELECT '河南司法警官职业学院' UNION ALL
    SELECT '鹤壁职业技术学院' UNION ALL
    SELECT '焦作师范高等专科学校' UNION ALL
    SELECT '河南检察职业学院' UNION ALL
    SELECT '河南质量工程职业学院' UNION ALL
    SELECT '郑州信息科技职业学院' UNION ALL
    SELECT '漯河医学高等专科学校' UNION ALL
    SELECT '南阳医学高等专科学校' UNION ALL
    SELECT '商丘医学高等专科学校' UNION ALL
    SELECT '郑州电子信息职业技术学院' UNION ALL
    SELECT '信阳职业技术学院' UNION ALL
    SELECT '嵩山少林武术职业学院' UNION ALL
    SELECT '郑州工业安全职业学院' UNION ALL
    SELECT '永城职业学院' UNION ALL
    SELECT '河南经贸职业学院' UNION ALL
    SELECT '河南交通职业技术学院' UNION ALL
    SELECT '河南农业职业学院' UNION ALL
    SELECT '郑州旅游职业学院' UNION ALL
    SELECT '郑州职业技术学院' UNION ALL
    SELECT '河南信息统计职业学院' UNION ALL
    SELECT '河南林业职业学院' UNION ALL
    SELECT '河南工业贸易职业学院' UNION ALL
    SELECT '郑州电力职业技术学院' UNION ALL
    SELECT '河南建筑职业技术学院' UNION ALL
    SELECT '郑州城市职业学院' UNION ALL
    SELECT '安阳职业技术学院' UNION ALL
    SELECT '新乡职业技术学院' UNION ALL
    SELECT '驻马店职业技术学院' UNION ALL
    SELECT '焦作工贸职业学院' UNION ALL
    SELECT '许昌陶瓷职业学院' UNION ALL
    SELECT '郑州理工职业学院' UNION ALL
    SELECT '郑州信息工程职业学院' UNION ALL
    SELECT '长垣烹饪职业技术学院' UNION ALL
    SELECT '开封文化艺术职业学院' UNION ALL
    SELECT '河南应用技术职业学院' UNION ALL
    SELECT '河南艺术职业学院' UNION ALL
    SELECT '河南机电职业学院' UNION ALL
    SELECT '河南护理职业学院' UNION ALL
    SELECT '许昌电气职业学院' UNION ALL
    SELECT '信阳涉外职业技术学院' UNION ALL
    SELECT '鹤壁汽车工程职业学院' UNION ALL
    SELECT '南阳职业学院' UNION ALL
    SELECT '郑州商贸旅游职业学院' UNION ALL
    SELECT '河南推拿职业学院' UNION ALL
    SELECT '洛阳职业技术学院' UNION ALL
    SELECT '郑州幼儿师范高等专科学校' UNION ALL
    SELECT '安阳幼儿师范高等专科学校' UNION ALL
    SELECT '郑州黄河护理职业学院' UNION ALL
    SELECT '河南医学高等专科学校' UNION ALL
    SELECT '郑州财税金融职业学院' UNION ALL
    SELECT '南阳农业职业学院' UNION ALL
    SELECT '洛阳科技职业学院' UNION ALL
    SELECT '鹤壁能源化工职业学院' UNION ALL
    SELECT '平顶山文化艺术职业学院' UNION ALL
    SELECT '濮阳医学高等专科学校' UNION ALL
    SELECT '驻马店幼儿师范高等专科学校' UNION ALL
    SELECT '三门峡社会管理职业学院' UNION ALL
    SELECT '河南轻工职业学院' UNION ALL
    SELECT '河南测绘职业学院' UNION ALL
    SELECT '信阳航空职业学院' UNION ALL
    SELECT '郑州卫生健康职业学院' UNION ALL
    SELECT '河南物流职业学院' UNION ALL
    SELECT '河南地矿职业学院' UNION ALL
    SELECT '郑州亚欧交通职业学院' UNION ALL
    SELECT '河南女子职业学院' UNION ALL
    SELECT '河南对外经济贸易职业学院' UNION ALL
    SELECT '濮阳石油化工职业技术学院' UNION ALL
    SELECT '南阳科技职业学院' UNION ALL
    SELECT '兰考三农职业学院' UNION ALL
    SELECT '汝州职业技术学院' UNION ALL
    SELECT '林州建筑职业技术学院' UNION ALL
    SELECT '郑州电子商务职业学院' UNION ALL
    SELECT '郑州轨道工程职业学院' UNION ALL
    SELECT '郑州体育职业学院' UNION ALL
    SELECT '洛阳文化旅游职业学院' UNION ALL
    SELECT '周口文理职业学院' UNION ALL
    SELECT '信阳艺术职业学院' UNION ALL
    SELECT '郑州城建职业学院' UNION ALL
    SELECT '郑州医药健康职业学院' UNION ALL
    SELECT '平顶山职业技术学院' UNION ALL
    SELECT '南阳工艺美术职业学院' UNION ALL
    SELECT '濮阳科技职业学院' UNION ALL
    SELECT '商丘幼儿师范高等专科学校' UNION ALL
    SELECT '周口理工职业学院' UNION ALL
    SELECT '焦作新材料职业学院' UNION ALL
    SELECT '开封职业学院' UNION ALL
    SELECT '洛阳商业职业学院' UNION ALL
    SELECT '郑州软件职业技术学院' UNION ALL
    SELECT '郑州智能科技职业学院' UNION ALL
    SELECT '郑州食品工程职业学院' UNION ALL
    SELECT '郑州汽车工程职业学院' UNION ALL
    SELECT '驻马店农业工程职业学院' UNION ALL
    SELECT '信阳科技职业学院' UNION ALL
    SELECT '信阳工程职业学院' UNION ALL
    SELECT '周口城市职业学院' UNION ALL
    SELECT '河南新乡工商职业学院' UNION ALL
    SELECT '开封工程职业学院' UNION ALL
    SELECT '开封智慧健康职业学院' UNION ALL
    SELECT '周口智慧能源职业学院' UNION ALL
    SELECT '平顶山科技职业学院'
) v;

-- 给本省还没有任何校区的学校补一个「主校区」。
-- 现有 231 个校区里有 121 个叫「主校区」，沿用同一约定；这样学校在「省-校-校区」三级
-- 联动里才可选（没有校区的学校用户根本选不中）。
INSERT INTO campus (school_id, name, status)
SELECT s.id, '主校区', 1
FROM school s
JOIN province p ON p.id = s.province_id
WHERE p.name = '河南'
  AND s.deleted = 0
  AND NOT EXISTS (SELECT 1 FROM campus c WHERE c.school_id = s.id AND c.deleted = 0);
